### PR TITLE
Feature: appointments dashboard

### LINKED ISSUE #11: Feature: appointments dashboard
#### Description

The appointments dashboard will help doctors approve and cancel appointments as well as join and reschedule appointments.

#### Tasks

- [x] Design appointments dashboard
- [x] Add integration to appointments dashboard

#### Developer Notes

N/A

#### Related Issues

N/A

### PR DESCRIPTION
**Pull request by fredshema**
#### What does this PR do?

This PR includes designs and implementation of the appointments dashboard page.

#### Description of Task to be completed?

- Design appointments dashboard page
- Implement requests, upcoming and cancelled appointments from supabase.
- Implement appointments approval and cancellation

#### How should this be manually tested?

Start the mobile and book a doctor you used logging in the back office. After an appointment is created refresh on the appointments page, the appointment should be in the appointment requests card. Try approving it and it should be changed to the upcoming appointments card. Try to cancel it and it should be transferred in the cancelled card.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

### CODE REVIEW

**Review by justinmihigo — COMMENTED** [review]
This is great, and if possible you can consider fetching those upcoming appointments on a user dashboard

**Comment by fredshema** [comment]
@justinmihigo I added fetching upcoming appointments to the dashboard.

**Review by justinmihigo — APPROVED** [review]

**Comment by Latiah** [comment]
hey @fredshema  on my end I was not able to deny or approve an appointment but I saw it under the requests . I do not know 
 happened maybe you can tell me what I missed.

**Comment by fredshema** [comment]
> hey @fredshema on my end I was not able to deny or approve an appointment but I saw it under the requests . I do not know happened maybe you can tell me what I missed.

I hadn't created the update policy and during my testing i was disabling `Row Level Security` feature on supabase. Now I created the update policy and made sure updates are working well

**Comment by Latiah** [comment]
> > hey @fredshema on my end I was not able to deny or approve an appointment but I saw it under the requests . I do not know happened maybe you can tell me what I missed.
> 
> I hadn't created the update policy and during my testing i was disabling `Row Level Security` feature on supabase. Now I created the update policy and made sure updates are working well

let me check again

**Review by Latiah — APPROVED** [review]

**Comment by Adadie** [comment]
Hey @fredshema I created an appointment from the app. Saw it in the requests on web but after approving it, it's no where to be found

**Comment by Adadie** [comment]
Screenshot 2024-07-20 at 15 51 26
Screenshot 2024-07-20 at 16 31 08

**Comment by Adadie** [comment]
Screenshot 2024-07-20 at 16 31 08
Screenshot 2024-07-20 at 16 31 16

**Comment by fredshema** [comment]
> Hey @fredshema I created an appointment from the app. Saw it in the requests on web but after approving it, it's no where to be found

Hey @Adadie I checked and for me it appointments are being displayed after approving, may be it wasn't finished loading appointments, I added loading indicators to know if the request is finished then you can confirm that there are no appointments. Try to test it again and let me know if it is working well for you too.

**Pull request merged**
