### PR TITLE
Feature: Profile settings

### LINKED ISSUE #14: Feature: Edit profile
**Description**

This issue deals with editing the doctor's profile which includes editing the doctor's personal information like hospital or job role, changing password.

Tasks

- [x]  Design settings page
- [x]  Fetch data from the doctor's table
- [x]  Updating profile
- [x]  Retrieving reviews of the doctor
- [x]  Resetting password

### PR DESCRIPTION
**Pull request by Latiah**
**What does this PR do?**

This PR includes designs and implementations of the profile settings page.

**Description of Task to be completed?**
 
- [x]  Design settings page
- [x]   Fetch data from the doctor's table
- [x]   Updating profile
- [x]  Retrieving reviews of the doctor
- [x]  Resetting password

**How should this be manually tested?**
Start the app with **npm run dev** and open the link. Signup then click on settings on the dashboard. On the settings page, you can see reviews, edit your profile, and change your password

Any background context you want to provide?
First signup on this PR the existing account that was not created from this PR updating the profile won't work.
What are the relevant pivotal tracker/Trello stories?
N/A

Screenshots (if appropriate)
N/A

Questions:
N/A

### CODE REVIEW

**Review by justinmihigo — APPROVED** [review]
This is great on my end

**Review by 911samuel — APPROVED** [review]
Great work

**Comment by Adadie** [comment]
Hey @Latiah 
1. when I update the doctor profile the details aren't updated. When I navigate back the info I had prefilled in isn't prefilled
2. The button to navigate to the dashboard in the sidebar doesn't work
3. The image in the top profile doesn't display anything on the profile settings page

Below I added a screenshot of what I'm seeing for you reference

**Comment by Adadie** [comment]
Hey @Latiah 
1. when I update the doctor profile the details aren't updated. When I navigate back the info I had prefilled in isn't prefilled
2. The button to navigate to the dashboard in the sidebar doesn't work
3. The image in the top profile doesn't display anything on the profile settings page

Below I added a screenshot of what I'm seeing for you reference
Screenshot 2024-07-20 at 15 26 20

**Comment by Latiah** [comment]
> Hey @Latiah
> 
> 1. when I update the doctor profile the details aren't updated. When I navigate back the info I had prefilled in isn't prefilled
> 2. The button to navigate to the dashboard in the sidebar doesn't work
> 3. The image in the top profile doesn't display anything on the profile settings page
> 
> Below I added a screenshot of what I'm seeing for you reference Screenshot 2024-07-20 at 15 26 20

ooh, there are some things I added for the update to work please sign up again with a new user. For the image, you have to wait a bit as it is being loaded  from the database.

**Pull request merged**
